# Generated by Django 5.1.7 on 2025-03-28 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите название заметки', max_length=150, null=True, verbose_name='Название заметки')),
                ('note', models.TextField(help_text='Введите запись в дневник', verbose_name='Заметка о дне')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Введите дату создания', verbose_name='Дата создания')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['name', 'note'],
            },
        ),
    ]
